-- MySQL Script generated by MySQL Workbench
-- Tue Mar 24 11:27:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema stage_entreprise
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stage_entreprise
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stage_entreprise` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `stage_entreprise` ;

-- -----------------------------------------------------
-- Table `stage_entreprise`.`entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stage_entreprise`.`entreprise` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stage_entreprise`.`annonce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stage_entreprise`.`annonce` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `entreprise_id` INT NOT NULL,
  `sujet` LONGTEXT NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `remuneration` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_annonce_entreprise1_idx` (`entreprise_id` ASC) VISIBLE,
  CONSTRAINT `fk_annonce_entreprise1`
    FOREIGN KEY (`entreprise_id`)
    REFERENCES `stage_entreprise`.`entreprise` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stage_entreprise`.`etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stage_entreprise`.`etudiant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stage_entreprise`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stage_entreprise`.`contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `entreprise_id` INT NOT NULL,
  `etudiant_id` INT NOT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `annonce_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contact_entreprise_idx` (`entreprise_id` ASC) VISIBLE,
  INDEX `fk_contact_etudiant1_idx` (`etudiant_id` ASC) VISIBLE,
  INDEX `fk_contact_annonce1_idx` (`annonce_id` ASC) VISIBLE,
  CONSTRAINT `fk_contact_annonce1`
    FOREIGN KEY (`annonce_id`)
    REFERENCES `stage_entreprise`.`annonce` (`id`),
  CONSTRAINT `fk_contact_entreprise`
    FOREIGN KEY (`entreprise_id`)
    REFERENCES `stage_entreprise`.`entreprise` (`id`),
  CONSTRAINT `fk_contact_etudiant1`
    FOREIGN KEY (`etudiant_id`)
    REFERENCES `stage_entreprise`.`etudiant` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stage_entreprise`.`convention`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stage_entreprise`.`convention` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `annonce_id` INT NOT NULL,
  `etudiant_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_convention_annonce1_idx` (`annonce_id` ASC) VISIBLE,
  INDEX `fk_convention_etudiant1_idx` (`etudiant_id` ASC) VISIBLE,
  CONSTRAINT `fk_convention_annonce1`
    FOREIGN KEY (`annonce_id`)
    REFERENCES `stage_entreprise`.`annonce` (`id`),
  CONSTRAINT `fk_convention_etudiant1`
    FOREIGN KEY (`etudiant_id`)
    REFERENCES `stage_entreprise`.`etudiant` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stage_entreprise`.`enseignant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stage_entreprise`.`enseignant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stage_entreprise`.`visite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stage_entreprise`.`visite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `enseignant_id` INT NOT NULL,
  `entreprise_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_visite_enseignant1_idx` (`enseignant_id` ASC) VISIBLE,
  INDEX `fk_visite_entreprise1_idx` (`entreprise_id` ASC) VISIBLE,
  CONSTRAINT `fk_visite_enseignant1`
    FOREIGN KEY (`enseignant_id`)
    REFERENCES `stage_entreprise`.`enseignant` (`id`),
  CONSTRAINT `fk_visite_entreprise1`
    FOREIGN KEY (`entreprise_id`)
    REFERENCES `stage_entreprise`.`entreprise` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
